### ISSUE TITLE
Error if onHidden prop is undefined

### ISSUE THREAD

**Issue by brendanmc6** [atomiks/tippyjs-react#261]
Thanks for the awesome library! Small issue, should be an easy fix.

## Summary
When `onHidden` prop exists, but is set to `undefined`, it throws an error.
```
Cannot read property 'apply' of undefined
invokeHook
https://gqw8b.csb.app/node_modules/tippy.js/dist/tippy.chunk.esm.js:828:48
eval
https://gqw8b.csb.app/node_modules/tippy.js/dist/tippy.chunk.esm.js:1367:7
eval
https://gqw8b.csb.app/node_modules/tippy.js/dist/tippy.chunk.esm.js:907:9
```

## Example
When I define my own parent component with an optional `onHidden` prop, and I want pass that optional prop down to Tippy.
```jsx
const ParentComponent = ({ onHidden }) => {
  return (
    <Tippy onHidden={onHidden} ... /> // throws if onHidden is undefined!
  )
}
```

Workaround:
```jsx
const ParentComponent = ({ onHidden }) => {
  return (
    <Tippy {...(onHidden ? { onHidden } : {})} ... /> // optional spread to avoid passing undefined
  )
}
```

## Repro:
https://codesandbox.io/s/tippy-undefined-error-gqw8b?file=/src/App.tsx

I have ran into other unexpected behavior from `undefined` props but failed to document them. I think it is worth double checking that all props treat `property === undefined` the same as a prop not being passed at all.

**Comment by atomiks** [comment]
You're using an old version of the lib. Upgrade to the new one and it should be fixed!

**Comment by brendanmc6** [comment]
@atomiks Sorry for the confusion, however I've upgraded the codesandbox to 4.2.0, and my current project has 4.2.0, and the error is still reproducible...

https://codesandbox.io/s/tippy-undefined-error-gqw8b

**Comment by testos944** [comment]
Confirm I also have this issue in 4.2.0
